class WordExercise {
  final String word;
  final List<String> phonetics;
  final String definition;
  final String example;

  WordExercise({
    required this.word,
    required this.phonetics,
    this.definition = '',
    this.example = '',
  });

  // Lista ampliada (100+) de palabras comunes con ejemplos simples
  static final List<WordExercise> exercises = [
    WordExercise(word: 'hello', phonetics: ['həˈloʊ', 'hɛˈloʊ'], definition: 'Greeting', example: 'Hello, how are you?'),
    WordExercise(word: 'world', phonetics: ['wɜːrld'], definition: 'The earth', example: 'The world is big.'),
    WordExercise(word: 'apple', phonetics: ['ˈæpəl'], definition: 'A fruit', example: 'I like red apples.'),
    WordExercise(word: 'banana', phonetics: ['bəˈnænə'], definition: 'A fruit', example: 'Bananas are yellow.'),
    WordExercise(word: 'orange', phonetics: ['ˈɔːrɪndʒ'], definition: 'A fruit', example: 'Orange juice is fresh.'),
    WordExercise(word: 'grape', phonetics: ['ɡreɪp'], definition: 'A fruit', example: 'Grapes can be green.'),
    WordExercise(word: 'water', phonetics: ['ˈwɔːtər', 'ˈwɑːtər'], definition: 'A drink', example: 'Drink water every day.'),
    WordExercise(word: 'coffee', phonetics: ['ˈkɔːfi'], definition: 'A drink', example: 'Coffee wakes me up.'),
    WordExercise(word: 'tea', phonetics: ['tiː'], definition: 'A drink', example: 'Tea can be green or black.'),
    WordExercise(word: 'milk', phonetics: ['mɪlk'], definition: 'A drink', example: 'Milk is white.'),
    WordExercise(word: 'bread', phonetics: ['brɛd'], definition: 'Food', example: 'Bread is fresh.'),
    WordExercise(word: 'butter', phonetics: ['ˈbʌtər'], definition: 'Food', example: 'Butter melts.'),
    WordExercise(word: 'cheese', phonetics: ['tʃiːz'], definition: 'Food', example: 'Cheese is tasty.'),
    WordExercise(word: 'egg', phonetics: ['ɛɡ'], definition: 'Food', example: 'I eat an egg.'),
    WordExercise(word: 'rice', phonetics: ['raɪs'], definition: 'Food', example: 'Rice is common in Asia.'),
    WordExercise(word: 'pasta', phonetics: ['ˈpæstə'], definition: 'Food', example: 'Pasta with tomato sauce.'),
    WordExercise(word: 'chicken', phonetics: ['ˈtʃɪkɪn'], definition: 'Food', example: 'Grilled chicken is nice.'),
    WordExercise(word: 'fish', phonetics: ['fɪʃ'], definition: 'Food', example: 'Fish is healthy.'),
    WordExercise(word: 'meat', phonetics: ['miːt'], definition: 'Food', example: 'Meat can be beef or pork.'),
    WordExercise(word: 'vegetable', phonetics: ['ˈvɛdʒtəbəl'], definition: 'Food', example: 'Vegetables are green.'),
    WordExercise(word: 'fruit', phonetics: ['fruːt'], definition: 'Food', example: 'Fruit is sweet.'),
    WordExercise(word: 'lemon', phonetics: ['ˈlɛmən'], definition: 'A fruit', example: 'Lemon is sour.'),
    WordExercise(word: 'strawberry', phonetics: ['ˈstrɔːˌbɛri'], definition: 'A fruit', example: 'Strawberries are red.'),
    WordExercise(word: 'grapefruit', phonetics: ['ˈɡreɪpˌfruːt'], definition: 'A fruit', example: 'Grapefruit is bitter.'),
    WordExercise(word: 'potato', phonetics: ['pəˈteɪtoʊ'], definition: 'A vegetable', example: 'Potatoes can be fried.'),
    WordExercise(word: 'tomato', phonetics: ['təˈmeɪtoʊ', 'tɪˈmɑːtoʊ'], definition: 'A vegetable', example: 'Tomatoes are red.'),
    WordExercise(word: 'onion', phonetics: ['ˈʌnjən'], definition: 'A vegetable', example: 'Onions can make you cry.'),
    WordExercise(word: 'garlic', phonetics: ['ˈɡɑːrlɪk'], definition: 'A plant', example: 'Garlic has a strong smell.'),
    WordExercise(word: 'pepper', phonetics: ['ˈpɛpər'], definition: 'Spice', example: 'Black pepper is spicy.'),
    WordExercise(word: 'carrot', phonetics: ['ˈkærət'], definition: 'A vegetable', example: 'Carrots are orange.'),
    WordExercise(word: 'broccoli', phonetics: ['ˈbrɒkəli'], definition: 'A vegetable', example: 'Broccoli is healthy.'),
    WordExercise(word: 'cucumber', phonetics: ['ˈkjuːˌkʌmbər'], definition: 'A vegetable', example: 'Cucumbers are fresh.'),
    WordExercise(word: 'lettuce', phonetics: ['ˈlɛtɪs'], definition: 'A vegetable', example: 'Lettuce for salad.'),
    WordExercise(word: 'spinach', phonetics: ['ˈspɪnɪtʃ'], definition: 'A vegetable', example: 'Spinach is green.'),
    WordExercise(word: 'mushroom', phonetics: ['ˈmʌʃˌruːm'], definition: 'Fungus', example: 'Mushrooms are tasty.'),
    WordExercise(word: 'corn', phonetics: ['kɔːrn'], definition: 'A grain', example: 'Corn is yellow.'),
    WordExercise(word: 'cake', phonetics: ['keɪk'], definition: 'Dessert', example: 'Birthday cake.'),
    WordExercise(word: 'cookie', phonetics: ['ˈkʊki'], definition: 'Dessert', example: 'Chocolate chip cookie.'),
    WordExercise(word: 'chocolate', phonetics: ['ˈtʃɒklət'], definition: 'Dessert', example: 'Dark chocolate.'),
    WordExercise(word: 'ice cream', phonetics: ['aɪs kriːm'], definition: 'Dessert', example: 'I like vanilla ice cream.'),
    WordExercise(word: 'breakfast', phonetics: ['ˈbrɛkfəst'], definition: 'Meal', example: 'Breakfast at 8 am.'),
    WordExercise(word: 'lunch', phonetics: ['lʌntʃ'], definition: 'Meal', example: 'Lunch at noon.'),
    WordExercise(word: 'dinner', phonetics: ['ˈdɪnər'], definition: 'Meal', example: 'Dinner at 7 pm.'),
    WordExercise(word: 'morning', phonetics: ['ˈmɔːrnɪŋ'], definition: 'Time of day', example: 'Good morning!'),
    WordExercise(word: 'afternoon', phonetics: ['ˌæftərˈnuːn'], definition: 'Time of day', example: 'Good afternoon!'),
    WordExercise(word: 'evening', phonetics: ['ˈiːvnɪŋ'], definition: 'Time of day', example: 'Good evening!'),
    WordExercise(word: 'night', phonetics: ['naɪt'], definition: 'Time of day', example: 'Good night!'),
    WordExercise(word: 'sun', phonetics: ['sʌn'], definition: 'Star', example: 'The sun is bright.'),
    WordExercise(word: 'moon', phonetics: ['muːn'], definition: 'Satellite', example: 'The moon is full.'),
    WordExercise(word: 'star', phonetics: ['stɑːr'], definition: 'Star', example: 'Many stars in the sky.'),
    WordExercise(word: 'rain', phonetics: ['reɪn'], definition: 'Weather', example: 'It might rain.'),
    WordExercise(word: 'snow', phonetics: ['snoʊ'], definition: 'Weather', example: 'Snow is cold.'),
    WordExercise(word: 'wind', phonetics: ['wɪnd'], definition: 'Weather', example: 'The wind is strong.'),
    WordExercise(word: 'cloud', phonetics: ['klaʊd'], definition: 'Weather', example: 'Clouds are white.'),
    WordExercise(word: 'storm', phonetics: ['stɔːrm'], definition: 'Weather', example: 'Storms are loud.'),
    WordExercise(word: 'hot', phonetics: ['hɒt'], definition: 'Adjective', example: 'It is hot today.'),
    WordExercise(word: 'cold', phonetics: ['koʊld'], definition: 'Adjective', example: 'It is cold today.'),
    WordExercise(word: 'warm', phonetics: ['wɔːrm'], definition: 'Adjective', example: 'Warm weather.'),
    WordExercise(word: 'cool', phonetics: ['kuːl'], definition: 'Adjective', example: 'Cool breeze.'),
    WordExercise(word: 'car', phonetics: ['kɑːr'], definition: 'Vehicle', example: 'Drive a car.'),
    WordExercise(word: 'bus', phonetics: ['bʌs'], definition: 'Vehicle', example: 'Take the bus.'),
    WordExercise(word: 'train', phonetics: ['treɪn'], definition: 'Vehicle', example: 'Catch the train.'),
    WordExercise(word: 'plane', phonetics: ['pleɪn'], definition: 'Vehicle', example: 'Fly by plane.'),
    WordExercise(word: 'bicycle', phonetics: ['ˈbaɪsɪkəl'], definition: 'Vehicle', example: 'Ride a bicycle.'),
    WordExercise(word: 'motorcycle', phonetics: ['ˈmoʊtərˌsaɪkəl'], definition: 'Vehicle', example: 'A fast motorcycle.'),
    WordExercise(word: 'boat', phonetics: ['boʊt'], definition: 'Vehicle', example: 'Sail a boat.'),
    WordExercise(word: 'ship', phonetics: ['ʃɪp'], definition: 'Vehicle', example: 'A big ship.'),
    WordExercise(word: 'house', phonetics: ['haʊs'], definition: 'Home', example: 'A small house.'),
    WordExercise(word: 'apartment', phonetics: ['əˈpɑːrtmənt'], definition: 'Home', example: 'A modern apartment.'),
    WordExercise(word: 'room', phonetics: ['ruːm'], definition: 'Part of a house', example: 'A big room.'),
    WordExercise(word: 'door', phonetics: ['dɔːr'], definition: 'Part of a house', example: 'Open the door.'),
    WordExercise(word: 'window', phonetics: ['ˈwɪndoʊ'], definition: 'Part of a house', example: 'Close the window.'),
    WordExercise(word: 'table', phonetics: ['ˈteɪbəl'], definition: 'Furniture', example: 'A wooden table.'),
    WordExercise(word: 'chair', phonetics: ['tʃɛər'], definition: 'Furniture', example: 'Sit on the chair.'),
    WordExercise(word: 'bed', phonetics: ['bɛd'], definition: 'Furniture', example: 'Go to bed.'),
    WordExercise(word: 'sofa', phonetics: ['ˈsoʊfə'], definition: 'Furniture', example: 'A comfortable sofa.'),
    WordExercise(word: 'lamp', phonetics: ['læmp'], definition: 'Furniture', example: 'Turn on the lamp.'),
    WordExercise(word: 'book', phonetics: ['bʊk'], definition: 'Object', example: 'Read a book.'),
    WordExercise(word: 'pen', phonetics: ['pɛn'], definition: 'Object', example: 'Use a pen.'),
    WordExercise(word: 'pencil', phonetics: ['ˈpɛnsəl'], definition: 'Object', example: 'Sharpen the pencil.'),
    WordExercise(word: 'paper', phonetics: ['ˈpeɪpər'], definition: 'Object', example: 'White paper.'),
    WordExercise(word: 'notebook', phonetics: ['ˈnoʊtˌbʊk'], definition: 'Object', example: 'Write in the notebook.'),
    WordExercise(word: 'computer', phonetics: ['kəmˈpjuːtər'], definition: 'Device', example: 'Use a computer.'),
    WordExercise(word: 'phone', phonetics: ['foʊn'], definition: 'Device', example: 'Call on the phone.'),
    WordExercise(word: 'tablet', phonetics: ['ˈtæblɪt'], definition: 'Device', example: 'A new tablet.'),
    WordExercise(word: 'keyboard', phonetics: ['ˈkiːˌbɔːrd'], definition: 'Device', example: 'Type on the keyboard.'),
    WordExercise(word: 'mouse', phonetics: ['maʊs'], definition: 'Device', example: 'Click the mouse.'),
    WordExercise(word: 'screen', phonetics: ['skriːn'], definition: 'Device', example: 'A big screen.'),
    WordExercise(word: 'music', phonetics: ['ˈmjuːzɪk'], definition: 'Art', example: 'I like music.'),
    WordExercise(word: 'movie', phonetics: ['ˈmuːvi'], definition: 'Art', example: 'Watch a movie.'),
    WordExercise(word: 'song', phonetics: ['sɔːŋ'], definition: 'Art', example: 'A good song.'),
    WordExercise(word: 'picture', phonetics: ['ˈpɪktʃər'], definition: 'Art', example: 'A nice picture.'),
    WordExercise(word: 'color', phonetics: ['ˈkʌlər'], definition: 'Property', example: 'My favorite color is blue.'),
    WordExercise(word: 'red', phonetics: ['rɛd'], definition: 'Color', example: 'Red apple.'),
    WordExercise(word: 'blue', phonetics: ['bluː'], definition: 'Color', example: 'Blue sky.'),
    WordExercise(word: 'green', phonetics: ['ɡriːn'], definition: 'Color', example: 'Green grass.'),
    WordExercise(word: 'yellow', phonetics: ['ˈjɛloʊ'], definition: 'Color', example: 'Yellow sun.'),
    WordExercise(word: 'black', phonetics: ['blæk'], definition: 'Color', example: 'Black cat.'),
    WordExercise(word: 'white', phonetics: ['waɪt'], definition: 'Color', example: 'White snow.'),
    WordExercise(word: 'purple', phonetics: ['ˈpɜːrpəl'], definition: 'Color', example: 'Purple flower.'),
    WordExercise(word: 'pink', phonetics: ['pɪŋk'], definition: 'Color', example: 'Pink dress.'),
    WordExercise(word: 'brown', phonetics: ['braʊn'], definition: 'Color', example: 'Brown table.'),
    WordExercise(word: 'teacher', phonetics: ['ˈtiːtʃər'], definition: 'Person', example: 'The teacher is kind.'),
    WordExercise(word: 'student', phonetics: ['ˈstuːdənt'], definition: 'Person', example: 'The student studies hard.'),
    WordExercise(word: 'school', phonetics: ['skuːl'], definition: 'Place', example: 'Go to school.'),
    WordExercise(word: 'university', phonetics: ['ˌjuːnɪˈvɜːrsɪti'], definition: 'Place', example: 'She goes to university.'),
    WordExercise(word: 'work', phonetics: ['wɜːrk'], definition: 'Activity', example: 'I work from home.'),
    WordExercise(word: 'job', phonetics: ['dʒɒb'], definition: 'Activity', example: 'He got a new job.'),
    WordExercise(word: 'office', phonetics: ['ˈɒfɪs'], definition: 'Place', example: 'The office is busy.'),
    WordExercise(word: 'market', phonetics: ['ˈmɑːrkɪt'], definition: 'Place', example: 'Go to the market.'),
    WordExercise(word: 'store', phonetics: ['stɔːr'], definition: 'Place', example: 'Buy at the store.'),
    WordExercise(word: 'money', phonetics: ['ˈmʌni'], definition: 'Thing', example: 'Save money.'),
    WordExercise(word: 'bank', phonetics: ['bæŋk'], definition: 'Place', example: 'Go to the bank.'),
    WordExercise(word: 'time', phonetics: ['taɪm'], definition: 'Concept', example: 'Time is precious.'),
    WordExercise(word: 'day', phonetics: ['deɪ'], definition: 'Time', example: 'A sunny day.'),
    WordExercise(word: 'week', phonetics: ['wiːk'], definition: 'Time', example: 'One week.'),
    WordExercise(word: 'month', phonetics: ['mʌnθ'], definition: 'Time', example: 'A long month.'),
    WordExercise(word: 'year', phonetics: ['jɪər'], definition: 'Time', example: 'A new year.'),
    WordExercise(word: 'family', phonetics: ['ˈfæmɪli'], definition: 'Group', example: 'My family is big.'),
    WordExercise(word: 'friend', phonetics: ['frɛnd'], definition: 'Person', example: 'A best friend.'),
    WordExercise(word: 'mother', phonetics: ['ˈmʌðər'], definition: 'Person', example: 'My mother cooks.'),
    WordExercise(word: 'father', phonetics: ['ˈfɑːðər'], definition: 'Person', example: 'My father drives.'),
    WordExercise(word: 'brother', phonetics: ['ˈbrʌðər'], definition: 'Person', example: 'My brother plays.'),
    WordExercise(word: 'sister', phonetics: ['ˈsɪstər'], definition: 'Person', example: 'My sister sings.'),
    WordExercise(word: 'child', phonetics: ['tʃaɪld'], definition: 'Person', example: 'A child smiles.'),
    WordExercise(word: 'baby', phonetics: ['ˈbeɪbi'], definition: 'Person', example: 'A baby sleeps.'),
    WordExercise(word: 'city', phonetics: ['ˈsɪti'], definition: 'Place', example: 'A big city.'),
    WordExercise(word: 'country', phonetics: ['ˈkʌntri'], definition: 'Place', example: 'A large country.'),
    WordExercise(word: 'music', phonetics: ['ˈmjuːzɪk'], definition: 'Art', example: 'I love music.'),
    WordExercise(word: 'dance', phonetics: ['dæns'], definition: 'Art', example: 'They dance well.'),
    WordExercise(word: 'sing', phonetics: ['sɪŋ'], definition: 'Art', example: 'She can sing.'),
    WordExercise(word: 'read', phonetics: ['riːd'], definition: 'Action', example: 'Read a book.'),
    WordExercise(word: 'write', phonetics: ['raɪt'], definition: 'Action', example: 'Write a letter.'),
    WordExercise(word: 'speak', phonetics: ['spiːk'], definition: 'Action', example: 'Speak clearly.'),
    WordExercise(word: 'listen', phonetics: ['ˈlɪsən'], definition: 'Action', example: 'Listen carefully.'),
    WordExercise(word: 'watch', phonetics: ['wɒtʃ'], definition: 'Action', example: 'Watch TV.'),
    WordExercise(word: 'look', phonetics: ['lʊk'], definition: 'Action', example: 'Look here.'),
    WordExercise(word: 'see', phonetics: ['siː'], definition: 'Action', example: 'I see a bird.'),
    WordExercise(word: 'walk', phonetics: ['wɔːk'], definition: 'Action', example: 'Walk slowly.'),
    WordExercise(word: 'run', phonetics: ['rʌn'], definition: 'Action', example: 'Run fast.'),
    WordExercise(word: 'jump', phonetics: ['dʒʌmp'], definition: 'Action', example: 'Jump high.'),
    WordExercise(word: 'swim', phonetics: ['swɪm'], definition: 'Action', example: 'Swim in the pool.'),
    WordExercise(word: 'drive', phonetics: ['draɪv'], definition: 'Action', example: 'Drive safely.'),
    WordExercise(word: 'cook', phonetics: ['kʊk'], definition: 'Action', example: 'Cook dinner.'),
    WordExercise(word: 'eat', phonetics: ['iːt'], definition: 'Action', example: 'Eat slowly.'),
    WordExercise(word: 'drink', phonetics: ['drɪŋk'], definition: 'Action', example: 'Drink water.'),
    WordExercise(word: 'sleep', phonetics: ['sliːp'], definition: 'Action', example: 'Sleep well.'),
    WordExercise(word: 'open', phonetics: ['ˈoʊpən'], definition: 'Action', example: 'Open the door.'),
    WordExercise(word: 'close', phonetics: ['kloʊz'], definition: 'Action', example: 'Close the window.'),
    WordExercise(word: 'start', phonetics: ['stɑːrt'], definition: 'Action', example: 'Start now.'),
    WordExercise(word: 'stop', phonetics: ['stɒp'], definition: 'Action', example: 'Stop here.'),
    WordExercise(word: 'help', phonetics: ['hɛlp'], definition: 'Action', example: 'Help me please.'),
    WordExercise(word: 'learn', phonetics: ['lɜːrn'], definition: 'Action', example: 'Learn English.'),
  ];

  static WordExercise getRandomWord() {
    exercises.shuffle();
    return exercises.first;
  }
}
